#!/bin/bash

# Daniel M. Lofaro (dan@danlofaro.com)
export LD_LIBRARY_PATH=/usr/lib:

LL_PT_REF_CHAN='ll-robot-ctrl-pt'

FLAG_REMOTE=0
FLAG_SERVER=0

NAME_SERVER='ll-robot-ctrl-server'

REMOTE_ADDRESS='0.0.0.0'

MakeAch()
{
	ach -1 -C $LL_PT_REF_CHAN -m 10 -n 3000
        sudo chmod 777 /dev/shm/achshm-ll*
}

Kill()
{

        screen -X -S $NAME_SERVER kill
        sudo ach -U $LL_PT_REF_CHAN
        #sudo kill -9 $(pidof hubo-log)
}

Remote()
{

case "$1" in 
'kill')
	KillRemote
;;
*)
	MakeAch
        achd -r pull $REMOTE_ADDRESS $LL_PT_REF_CHAN &

;;
esac

}

KillRemote()
{
	sudo kill -9 $(pidof achd)
}

Start()
{
  MakeAch
  if [[ $FLAG_SERVER -eq 1 ]]
	   then
	       echo 'Starting Server'
	       StartServer
  fi

  if [[ $FLAG_SERVER -eq 0 ]]
           then 
	       echo 'Starting Client'
               StartClient
  fi
}

StartServer()
{
  screen -S $NAME_SERVER -d -m python ll_robot_ctrl_server.py
}



ShowUsage()
{
	echo
	echo 'start         : Start all channels and processes and consle'
        echo 'make          : makes all the ach channels'
	echo 'kill          : Emergency kill the daemon process'
	echo 'remote        : Starts a remote connection to xxx.xxx.xxx.xxx via achd'
	echo 'killremote    : kills the remote connection'
	echo
}


SetFlags()
{
HUBO_I=0
HUBO_TEMP1="$@"
HUBO_TEMP=($HUBO_TEMP1)
for var in "$@"
do
#    echo "$var"
    case "$var" in
      'server' )
          FLAG_SERVER=1
      ;;
      'remote' )
	  FLAG_REMOTE=1
          REMOTE_ADDRESS=${HUBO_TEMP[$(($HUBO_I+1))]}
	  echo "Remote address set: "$REMOTE_ADDRESS
      ;;
    esac
    HUBO_I=$(($HUBO_I+1))

done
}



SetFlags $@
case "$1" in
# Start all channels and processes
	'make' )
		MakeAch $@
	;;
# Start all channels and processes and Console
	'start' )
		Start $@
	;;

# Start remote via achd
	'remote' )
		Remote $2
	;;

# Kills remote connection
	'killremote' )
		KillRemote
	;;


# Kill all processies and remove ach
	'killall' )
		KillAll
	;;

# Emergency kill
	'kill' )
		Kill
	;;

	*)
		ShowUsage
		exit 1
	;;
esac

exit 0

# Local Variables:
#  indent-tabs-mode:t
#  tab-width: 8
#  c-basic-offset: 8
# End:
